# Generated by Django 5.2.3 on 2025-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='review_pictures/'),
        ),
    ]
