# Generated by Django 5.2 on 2025-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category_tags',
            field=models.TextField(blank=True, help_text='Comma-separated list of category tags'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lang_spoken',
            field=models.TextField(blank=True, help_text='Comma-separated list of languages spoken', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('organization', 'Organization')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_purpose',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('academic', 'Academic'), ('other', 'Other')], default='', max_length=100),
        ),
    ]
