# Generated by Django 5.2 on 2025-06-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service',
            new_name='Gig',
        ),
    ]
