# Generated by Django 5.2.3 on 2025-06-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bid_projectpost_bid_project'),
        ('base', '0002_review_picture'),
    ]

    operations = [
    ]
