# Generated by Django 5.2 on 2025-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_merge_20250619_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Gig',
            new_name='gig',
        ),
    ]
