# Generated by Django 5.2 on 2025-06-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_gig_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='user',
            new_name='freelancer',
        ),
    ]
